meson.build: fix missing dependency check for libxshmfence on wayland
When libxshmfence isn't present and xwayland not disabled explicitly, it
silently is enabled and causing the build to break.

FAILED: miext/sync/liblibxserver_miext_sync.a.p/misyncshm.c.o
cc -Imiext/sync/liblibxserver_miext_sync.a.p -Imiext/sync -I../miext/sync -IXext -I../Xext -IXi -I../Xi -Icomposite -I../composite -Idamageext -I../damageext -Iexa -I../exa -Ifb -I../fb -Iglamor -I../glamor -Imi -I../mi -Imiext/damage -I../miext/damage -Imiext/shadow -I../miext/shadow -Idbe -I../dbe -Idri3 -I../dri3 -Iinclude -I../include -Ipresent -I../present -Irandr -I../randr -Irender -I../render -Ixfixes -I../xfixes -I/home/nekrad/.usr/x11/include -I/home/nekrad/.usr/x11/include/X11/dri -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -DHAVE_DIX_CONFIG_H -fno-strict-aliasing -fvisibility=hidden -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fPIC -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -MD -MQ miext/sync/liblibxserver_miext_sync.a.p/misyncshm.c.o -MF miext/sync/liblibxserver_miext_sync.a.p/misyncshm.c.o.d -o miext/sync/liblibxserver_miext_sync.a.p/misyncshm.c.o -c ../miext/sync/misyncshm.c
../miext/sync/misyncshm.c:36:10: fatal error: X11/xshmfence.h: Datei oder Verzeichnis nicht gefunden
   36 | #include <X11/xshmfence.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>